name: Generate GitHub Metrics
on:
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: brijeshzzz
          template: classic
          base: header, activity, community, repositories, metadata

          ## Stable settings (NO recent analyzer = no crash)
          plugin_languages: yes
          plugin_languages_indepth: no
          plugin_languages_sections: most-used

          plugin_topics: yes
          plugin_topics_limit: 12
